# 평가(147p-174p)

In [1]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [3]:
class MyFakeClassifier(BaseEstimator):
    def fit(self,X,y):
        pass
    
    def predict(self,X):
        return np.zeros((len(X),1),dtype=bool)
    
digits=load_digits()

y=(digits.target==7).astype(int)
X_train,X_test,y_train,y_test=train_test_split(digits.data,y,random_state=11)

In [4]:
#불균형한 레이블 데이터 분포도 확인
print('레이블 테스트 세트 크기:',y_test.shape)
print('테스트 세트 레이블 0과 1의 분포도')
print(pd.Series(y_test).value_counts())

레이블 테스트 세트 크기: (450,)
테스트 세트 레이블 0과 1의 분포도
0    405
1     45
dtype: int64


In [5]:
#학습/예측/정확도 평가
fakeclf=MyFakeClassifier()
fakeclf.fit(X_train,y_train)
fakepred=fakeclf.predict(X_test)
print('모든 예측을 0으로 하여도 정확도는:{:.3f}'.format(accuracy_score(y_test,fakepred)))

모든 예측을 0으로 하여도 정확도는:0.900


In [6]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,fakepred)

array([[405,   0],
       [ 45,   0]], dtype=int64)

In [7]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

def get_clf_eval(y_test,pred):
    confusion=confusion_matrix(y_test,pred)
    accuracy=accuracy_score(y_test,pred)
    precision=precision_score(y_test,pred)
    recall=recall_score(y_test,pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}'.format(accuracy,precision,recall))

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

#titanic_df=pd.read_csv()
#y_titanic_df=titanic_df['Survived']
#X_titanic_df=titanic_df.drop('Survived',axis=1)
#X_titanic_df=transform_features(X_titanic_df)

#X_train,X_test,y_train,y_test=train_test_split(X_titanic_df,y_titanic_df,test_size=0.2,random_state=11)

lr_clf=LogisticRegression()

#lr_clf.fit(X_train,y_train)
#pred=lr_clf.predict(X_test)
#get_clf_eval(y_test,pred)

In [10]:
#예측확률 계산

#pred_proba=lr_clf.predict_proba(X_test)
#pred=lr_clf.predict(X_test)
#print('pred_proba()결과 Shape : {0}',format(pred_proba.shape))
#print('pred_proba array에서 앞 3개만 샘플로 추출 \n:',pred_proba[:3])

#pred_proba_result=np.concatenate([pred_proba,pred.reshape(-1,1)],axis=1)
#print('두 개의 class 중에서 더 큰 확률을 클래스 값으로 예측 \n',pred_proba_result[:3])

In [11]:
from sklearn.preprocessing import Binarizer
X=[[1,-1,2],
  [2,0,0],
  [0,1.1,1.2]]

binarizer=Binarizer(threshold=1.1)
print(binarizer.fit_transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [15]:
from sklearn.preprocessing import Binarizer

#custom_threshold=0.5

#pred_proba_1=pred_proba[:,1].reshape(-1,1)

#binarizer=Binarizer(threshold=custom_threshold).fit(pred_proba_1)
#custom_predict=binarizer.transform(pred_proba_1)

#get_clf_eval(y_test,custom_predict)

In [16]:
#임곗값 변화에 따른 평가

#theresholds=[0.4,0.45,0.5,0.55,0.6]

#def get_eval_by_threshold(y_test,pred_proba_c1,thresholds):
#   for custom_threshold in thresholds:
#     binarier=Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
#     custom_predict=binarizer.transform(pred_proba_c1)
#     print('임곗값:',custom_theshold)
#     get_clf_eval(y_test,custom_predict)

#get_eval_by_threshold(y_test,pred_proba[:,1].reshape(-1,1),thresholds)



In [20]:
from sklearn.metrics import f1_score
#f1=f1_score(y_test,pred)
#print('F1 스코어: {0:.4f}'.format(f1))

#함수 작성
#def get_clf_eval(y_test,pred):
#    confusion=confusion_matrix(y_test,pred)
#    accuracy=accuracy_score(y_test,pred)
#    precision=precision_score(y_test,pred)
#    recall=recall_score(y_test,pred)
    
#    f1= f1_score(y_test,pred)
#    print('오차행렬')
#    print(consfution)

#    roc_auc=roc_auc_score(y_test,pred_proba)
#    print('오차행렬')
#    print(confusion)

#    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, F1:{3:.4f}, AUC:{4:.4f}'.format(accuracy,precision,recall,f1,roc_auc))


#thresholds=[0.4,0.45,0.5,0.55,0.6]
#pred_proba=lr_clf.predict_proba(X_test)
#get_eval_by_threshold(y_test,pred_proba[:,1],reshape(-1,1),threholds)



In [21]:
from sklearn.metrics import roc_curve

#pred_proba_class1=lr_clf.predict_proba(X_test)[:,1]

#시각화
def roc_curve_plot(y_test,pred_proba_c1):
    fprs,tprs,thresholds=roc_curve(y_test,pred_proba_c1)
    plt.plot(fprs,tprslabel='ROC')
    plot.plot([0,1],[0,1],'k--',label='Random')
    
    start,end=plt.xlim()
    plt.sticks(np.round(np.arrange(start,end,0.1),2))
    plt.xlim(0,1);plt.ylim(0,1)
    plt.xlabel('FPR(1-Sensitivity)');plt.ylabel('TPR(Recall)')
    plt.legend()
    
#roc_curve_plot(y_test,pred[:,1])