In [40]:
import numpy as np

array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

print('array1: {:0}차원'.format(array1.ndim))

list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2:',array2.shape)

array1d=np.arange(1,10)
print(array1d)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print(array3)

array33 = array1d[array1d > 5]
print(array1d)
print(array33)

array_boo=np.arange(1,4)
boolean_indexes=np.array([False,False,True])
arrage_booo=array_boo[boolean_indexes]
print(arrage_booo)

array2d=np.array([[8,12],[7,1]])
print(array2d)
sort_array2d_axis0=np.sort(array2d,axis=0)
print(sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print(sort_array2d_axis1)

A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

dot_product=np.dot(A,B)
print(dot_product)

transpose_mat=np.transpose(A)
print(transpose_mat)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array1: 1차원
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
[0 1 2 3 4 5 6 7 8 9]
array2: (2, 5)
[1 2 3 4 5 6 7 8 9]
[3 6]
[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[3]
[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]
[[ 58  64]
 [139 154]]
[[1 4]
 [2 5]
 [3 6]]
